name: Build jsgeoda 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@geodacenter'

    - name: Build&Test jsgeoda
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        # replace ${GITHUB_TOKEN} in .npmrc
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    # Publish to GitHub Package Registry
    - name: Publish to GitHub Package Registry
      # Only when release
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        npm publish
      env:
        # replace ${GITHUB_TOKEN} in .npmrc
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    # Publish to NPM registry
    - name: Publish to NPM Registry
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
      run: |
        rm .npmrc
        echo //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN > .npmrc
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
