name: Build jsgeoda 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Build&Test jsgeoda
        run: |
          npm install
          npm run build --if-present
          npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: publis-npm
        #if: startsWith(github.ref, 'refs/tags/v')
        run: |
          npm install
          npm run build --if-present
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@geodacenter'
      - name: publish-gpr
        #if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN} > .npmrc
          echo @geodacenter:registry=https://npm.pkg.github.com >> .npmrc
          echo always-auth=true >> .npmrc
          npm install
          npm run build --if-present
          npm publish
        env:
          # replace ${GITHUB_TOKEN} in .npmrc
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}